query fetchMoreTasks($after: String, $first: Int) {
  tasks(after: $after, first: $first) {
    edges {
      node {
        id
        title
        description
        tags
        color
        dueDate
        remindMeAt
        completedAt
        index
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
