query getTasks($first: Int) {
  tasks(first: $first) {
    edges {
      node {
        id
        title
        description
        tags
        color
        dueDate
        remindMeAt
        completedAt
        index
      }
    }
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
  }
  taskTags {
    tags
  }
  allTasks: tasks {
    totalCount
  }
  allTaskTags: taskTags {
    tags
  }
}
