mutation updateTask($input: UpdateTaskInput!) {
  updateTask(input: $input) {
    task {
      id
      title
      description
      tags
      color
      startDate
      dueDate
      remindMeAt
      completedAt
      index
    }
  }
}
